#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Sat Sep 07 18:32:03 2013
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

import midi

class KeyboardDisplay(wx.Window):
    def __init__(self, parent, ID):
        wx.Window.__init__(self, parent, ID)
        self.parent = parent
        self.hwnd = self.GetHandle()
        
        self.timer = wx.Timer(self)
        self.Bind(wx.EVT_TIMER, self.update, self.timer)
        self.Bind(wx.EVT_LEFT_DOWN, self.onClick)
        self.Bind(wx.EVT_LEFT_UP, self.offClick)
        self.Bind(wx.EVT_KEY_DOWN, self.onKey)
        self.Bind(wx.EVT_KEY_UP, self.offKey)
        
        self.fps = 60.0
        self.timespacing = 1000.0 / self.fps
        self.timer.Start(self.timespacing, False)

    def update(self, event):
        # process pygame.midi events
        pass
        
    def onClick(self, event):
        pass
        
    def offClick(self, event):
        pass
        
    def onKey(self, event):
        pass
        
    def offKey(self, event):
        pass
        
    def kill(self, event):
        # Make sure Pygame can't be asked to redraw /before/ quitting by unbinding all methods which
        # call the Redraw() method
        # (Otherwise wx seems to call Draw between quitting Pygame and destroying the frame)
        # This may or may not be necessary now that Pygame is just drawing to surfaces
        self.Unbind(event = wx.EVT_TIMER, handler = self.update, 
            source = self.timer)
        self.Unbind(event = wx.EVT_LEFT_DOWN, handler = self.onClick)
        self.Unbind(event = wx.EVT_LEFT_UP, handler = self.offClick)
        self.Unbind(event = wx.EVT_KEY_DOWN, handler = self.onKey)
        self.Unbind(event = wx.EVT_KEY_UP, handler = self.offKey)

class Instrument(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Instrument.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.window_1 = KeyboardDisplay(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Instrument.__set_properties
        self.SetTitle(_("Instrument"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Instrument.__do_layout
        sizer_17 = wx.BoxSizer(wx.VERTICAL)
        sizer_17.Add(self.window_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_17)
        sizer_17.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Instrument
class Root(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Root.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook = wx.Notebook(self, wx.ID_ANY, style=0)
        self.notebook_devices = wx.Panel(self.notebook, wx.ID_ANY)
        self.list_box_input = wx.ListBox(self.notebook_devices, wx.ID_ANY, choices=[])
        self.sizer_5_staticbox = wx.StaticBox(self.notebook_devices, wx.ID_ANY, _("Input"))
        self.list_box_output = wx.ListBox(self.notebook_devices, wx.ID_ANY, choices=[], style=wx.LB_SINGLE)
        self.sizer_6_staticbox = wx.StaticBox(self.notebook_devices, wx.ID_ANY, _("Output"))
        self.button_connect = wx.Button(self.notebook_devices, wx.ID_ANY, _("Connect"))
        self.button_refresh = wx.Button(self.notebook_devices, wx.ID_ANY, _("Refresh"))
        self.button_disconnect = wx.Button(self.notebook_devices, wx.ID_ANY, _("Disconnect"))
        self.notebook_rules = wx.Panel(self.notebook, wx.ID_ANY)
        self.label_2 = wx.StaticText(self.notebook_rules, wx.ID_ANY, _("Type:"))
        self.combo_box_1 = wx.ComboBox(self.notebook_rules, wx.ID_ANY, choices=[_("Scale"), _("Chord"), _("Chord Progression")], style=wx.CB_DROPDOWN)
        self.label_1 = wx.StaticText(self.notebook_rules, wx.ID_ANY, _("Name:"))
        self.text_ctrl_3 = wx.TextCtrl(self.notebook_rules, wx.ID_ANY, "")
        self.label_3 = wx.StaticText(self.notebook_rules, wx.ID_ANY, _("New Rule:"))
        self.text_ctrl_2 = wx.TextCtrl(self.notebook_rules, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.label_4 = wx.StaticText(self.notebook_rules, wx.ID_ANY, _("Rules:"))
        self.list_box_1 = wx.ListBox(self.notebook_rules, wx.ID_ANY, choices=[])
        self.notebook_play = wx.Panel(self.notebook, wx.ID_ANY)
        self.label_program = wx.StaticText(self.notebook_play, wx.ID_ANY, _("Program:"))
        self.combo_box_2 = wx.ComboBox(self.notebook_play, wx.ID_ANY, choices=[_("Scales"), _("Chords"), _("Chord Progressions"), _("Improvise")], style=wx.CB_DROPDOWN)
        self.label_rules = wx.StaticText(self.notebook_play, wx.ID_ANY, _("Rules:"))
        self.list_box_2 = wx.ListBox(self.notebook_play, wx.ID_ANY, choices=[])
        self.label_info = wx.StaticText(self.notebook_play, wx.ID_ANY, _("Info:"))
        self.label_5 = wx.StaticText(self.notebook_play, wx.ID_ANY, "")
        self.button_play = wx.Button(self.notebook_play, wx.ID_ANY, _("Start..."))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LISTBOX, self.select_input_id, self.list_box_input)
        self.Bind(wx.EVT_LISTBOX, self.select_output_id, self.list_box_output)
        self.Bind(wx.EVT_BUTTON, self.connect_devices, self.button_connect)
        self.Bind(wx.EVT_BUTTON, self.refresh_devices, self.button_refresh)
        self.Bind(wx.EVT_BUTTON, self.disconnect_devices, self.button_disconnect)
        self.Bind(wx.EVT_BUTTON, self.start_instrument, self.button_play)
        # end wxGlade
        
        self.input_id = None
        self.output_id = None

    def __set_properties(self):
        # begin wxGlade: Root.__set_properties
        self.SetTitle(_("Music Tutor"))
        self.SetSize((400, 300))
        self.button_connect.Enable(False)
        self.button_disconnect.Enable(False)
        self.combo_box_1.SetSelection(-1)
        self.text_ctrl_2.SetFocus()
        self.combo_box_2.SetSelection(-1)
        # end wxGlade
        
        self.update_devices()

    def __do_layout(self):
        # begin wxGlade: Root.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_16 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.VERTICAL)
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_6_staticbox.Lower()
        sizer_6 = wx.StaticBoxSizer(self.sizer_6_staticbox, wx.HORIZONTAL)
        self.sizer_5_staticbox.Lower()
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.HORIZONTAL)
        sizer_5.Add(self.list_box_input, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_5, 2, wx.EXPAND, 0)
        sizer_6.Add(self.list_box_output, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_6, 2, wx.EXPAND, 0)
        sizer_7.Add(self.button_connect, 1, wx.EXPAND, 0)
        sizer_7.Add(self.button_refresh, 1, wx.EXPAND, 0)
        sizer_7.Add(self.button_disconnect, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_7, 1, wx.EXPAND, 0)
        self.notebook_devices.SetSizer(sizer_4)
        sizer_14.Add(self.label_2, 0, 0, 0)
        sizer_14.Add(self.combo_box_1, 1, wx.EXPAND, 0)
        sizer_11.Add(sizer_14, 1, wx.EXPAND, 0)
        sizer_13.Add(self.label_1, 0, wx.EXPAND, 0)
        sizer_13.Add(self.text_ctrl_3, 1, wx.EXPAND, 0)
        sizer_11.Add(sizer_13, 1, wx.EXPAND, 0)
        sizer_11.Add(self.label_3, 0, 0, 0)
        sizer_11.Add(self.text_ctrl_2, 6, wx.EXPAND, 0)
        sizer_2.Add(sizer_11, 2, wx.EXPAND, 0)
        sizer_3.Add(self.label_4, 0, 0, 0)
        sizer_3.Add(self.list_box_1, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        self.notebook_rules.SetSizer(sizer_2)
        sizer_10.Add(self.label_program, 0, 0, 0)
        sizer_10.Add(self.combo_box_2, 1, wx.EXPAND, 0)
        sizer_9.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_12.Add(self.label_rules, 0, 0, 0)
        sizer_12.Add(self.list_box_2, 1, wx.EXPAND, 0)
        sizer_9.Add(sizer_12, 5, wx.EXPAND, 0)
        sizer_15.Add(self.label_info, 0, 0, 0)
        sizer_15.Add(self.label_5, 1, wx.ALL | wx.EXPAND, 0)
        sizer_9.Add(sizer_15, 1, wx.EXPAND, 0)
        sizer_8.Add(sizer_9, 2, wx.EXPAND, 0)
        sizer_16.Add(self.button_play, 1, wx.EXPAND, 0)
        sizer_8.Add(sizer_16, 1, wx.EXPAND, 0)
        self.notebook_play.SetSizer(sizer_8)
        self.notebook.AddPage(self.notebook_devices, _("Devices"))
        self.notebook.AddPage(self.notebook_rules, _("Rules"))
        self.notebook.AddPage(self.notebook_play, _("Play"))
        sizer_1.Add(self.notebook, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def connect_devices(self, event):  # wxGlade: Root.<event_handler>
        print "Event handler 'connect_devices' not implemented!"
        self.button_disconnect.Enable(True)
        self.button_connect.Enable(False)
        event.Skip()

    def refresh_devices(self, event):  # wxGlade: Root.<event_handler>
        self.update_devices()
        event.Skip()

    def disconnect_devices(self, event):  # wxGlade: Root.<event_handler>
        print "Event handler 'disconnect_devices' not implemented!"
        self.button_connect.Enable(True)
        self.button_disconnect.Enable(False)
        event.Skip()

    def start_instrument(self, event):  # wxGlade: Root.<event_handler>
        print "Event handler 'start_instrument' not implemented!"
        event.Skip()
        
    def update_devices(self):
        input_devices, output_devices = midi.get_devices(True)
        self.list_box_input.Clear()
        self.list_box_input.AppendItems(input_devices)
        self.list_box_output.Clear()
        self.list_box_output.AppendItems(output_devices)

    def select_input_id(self, event):  # wxGlade: Root.<event_handler>
        device = self.list_box_input.GetStringSelection()
        self.input_id = int(device.split()[0])
        print 'input id: %s' % self.input_id
        if self.output_id != None:
            self.button_connect.Enable(True)
        event.Skip()
    
    def select_output_id(self, event):  # wxGlade: Root.<event_handler>
        device = self.list_box_output.GetStringSelection()
        self.output_id = int(device.split()[0])
        print 'output id: %s' % self.output_id
        if self.input_id != None:
            self.button_connect.Enable(True)
        event.Skip()
# end of class Root

if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = Root(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()